- setup:

- name: Stop promtail
  systemd:
    scope: user
    name: "{{ ya_requestor_yagna_unit_name }}-promtail"
    enabled: no
    state: stopped
  ignore_errors: yes  # go on if unit doesn't exist

- name: Stop ya-requestor yagna
  systemd:
    scope: user
    name: "{{ ya_requestor_yagna_unit_name }}"
    enabled: no
    state: stopped
  ignore_errors: yes  # go on if unit doesn't exist

- name: Stop simple watchdog timer
  systemd:
    scope: user
    name: "{{ ya_requestor_unit_base_name }}_simple_watchdog.timer"
    enabled: no
    state: stopped
  ignore_errors: yes  # go on if unit doesn't exist

- name: Stop simple watchdog service
  systemd:
    scope: user
    name: "{{ ya_requestor_unit_base_name }}_simple_watchdog.service"
    state: stopped
  ignore_errors: yes  # go on if unit doesn't exist

- name: Delete requestor dir
  file:
    path: "{{ ya_requestor_dir }}"
    state: absent

- name: Delete systemd unit
  file:
    dest: "{{ ansible_user_dir }}/.config/systemd/user/{{ item }}"
    state: absent
  loop:
    - "{{ ya_requestor_yagna_unit_name }}-promtail.service"
    - "{{ ya_requestor_yagna_unit_name }}.service"
    - "{{ ya_requestor_unit_base_name }}_simple_watchdog.service"
    - "{{ ya_requestor_unit_base_name }}_simple_watchdog.timer"

- name: Reload systemd
  systemd:
    scope: user
    daemon_reload: yes
